### ISSUE TITLE
the submit button on the demo is disabled 

### ISSUE THREAD

**Issue by jingyi-zhao-01** [run-llama/ts-playground#2]
![image](https://github.com/run-llama/ts-playground/assets/25937657/3b1d231b-20d8-423e-9b9a-7b86463187db)
- the button seems to be disabled

**Comment by yisding** [comment]
Hi! You need to tap the "Build Vector Index" button first. I'm open to other UI ideas though if you have them. The reason I made it two step is the Build Vector Index step takes a while.
